package main

import (
	"fmt"
	"strings"
	"time"

	"github.com/Marguelgtz/Stint/internal/deep"
)

// buildHandoff renders the session's truthful handoff. It distinguishes
// verified evidence, worker claims, and unresolved uncertainty — a partially
// completed mission with an honest handoff is a valid Deep Work outcome.
func buildHandoff(s deep.DeepState, reason string, now time.Time, finalVerify string, repo deep.RepoSummary) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Deep Work Handoff — %s\n\n", s.MissionName)
	fmt.Fprintf(&b, "| | |\n| --- | --- |\n")
	fmt.Fprintf(&b, "| Session | `%s` |\n", s.SessionID)
	fmt.Fprintf(&b, "| Phase | %s (%s) |\n", s.Phase, reason)
	fmt.Fprintf(&b, "| Started | %s |\n", s.StartedAt.Format(time.RFC3339))
	if s.LandedAt != nil {
		fmt.Fprintf(&b, "| Landed | %s |\n", s.LandedAt.Format(time.RFC3339))
	}
	fmt.Fprintf(&b, "| Configured deadline | %s |\n", s.Deadline.Format(time.RFC3339))
	fmt.Fprintf(&b, "| Actual duration | %s |\n", now.Sub(s.StartedAt).Round(time.Second))

	b.WriteString("\n## Mission\n\n")
	fmt.Fprintf(&b, "%s\n", s.Objective)
	if len(s.Success) > 0 {
		b.WriteString("\nSuccess criteria:\n\n")
		for _, sc := range s.Success {
			fmt.Fprintf(&b, "- %s\n", sc)
		}
	}
	if len(s.Constraints) > 0 {
		b.WriteString("\nConstraints:\n\n")
		for _, c := range s.Constraints {
			fmt.Fprintf(&b, "- %s\n", c)
		}
	}

	b.WriteString("\n## Tasks\n\n")
	b.WriteString("| ID | Objective | Status | Attempts | Evidence |\n")
	b.WriteString("| --- | --- | --- | --- | --- |\n")
	for _, t := range s.Tasks {
		fmt.Fprintf(&b, "| %s | %s | %s | %d | %s |\n",
			t.ID, truncate(t.Objective, 60), taskHandoffStatus(s, t), t.Attempts, taskHandoffEvidence(s, t))
	}

	b.WriteString("\n## Verification\n\n")
	switch {
	case s.Verify == "":
		b.WriteString("The mission defines no verification command; task results above reflect worker reports (unverified by the coordinator).\n")
	case finalVerify == "":
		b.WriteString("Final verification did not run.\n")
	default:
		trimmed := strings.TrimSpace(finalVerify)
		if len(trimmed) > 2000 {
			trimmed = trimmed[len(trimmed)-2000:]
		}
		fmt.Fprintf(&b, "Final run of `%s`:\n\n```\n%s\n```\n", s.Verify, trimmed)
	}

	b.WriteString("\n## Workspace\n\n")
	fmt.Fprintf(&b, "- repository: `%s`\n", s.RepoPath)
	fmt.Fprintf(&b, "- worktree: `%s` (left in place for review)\n", s.WorktreePath)
	fmt.Fprintf(&b, "- branch: `%s`\n", s.Branch)
	if repo.HeadCommit != "" {
		fmt.Fprintf(&b, "- head: `%s`\n", repo.HeadCommit)
	}
	if strings.TrimSpace(repo.DiffStat) != "" {
		b.WriteString("\nDiff vs session base:\n\n```\n" + repo.DiffStat + "\n```\n")
	}

	b.WriteString("\n## Remaining work & next action\n\n")
	remaining := false
	for _, t := range s.Tasks {
		switch t.Status {
		case deep.StatusVerified:
			continue
		}
		remaining = true
		fmt.Fprintf(&b, "- **%s** (%s): %s\n", t.ID, t.Status, t.Objective)
		if t.Blocker != "" {
			fmt.Fprintf(&b, "  - blocker: %s\n", t.Blocker)
		}
	}
	if !remaining {
		b.WriteString("All tasks reached a terminal state. Review the branch and merge or discard.\n")
	} else {
		fmt.Fprintf(&b, "Recommended next action: review branch `%s`, inspect the worktree above,\n", s.Branch)
		b.WriteString("and resume the remaining tasks (re-run with the same mission or finish by hand).\n")
	}
	b.WriteString("\nThis handoff was generated by Stint Deep Work. Worker claims are labeled; only the\nverification section and per-task evidence reflect coordinator-checked results.\n")
	return b.String()
}

func taskHandoffStatus(s deep.DeepState, t deep.Task) string {
	if t.Status == deep.StatusVerified && s.Verify == "" {
		return "verified (unverified: no verify command; worker report)"
	}
	if t.Status == deep.StatusBlocked {
		return "blocked"
	}
	return string(t.Status)
}

func taskHandoffEvidence(s deep.DeepState, t deep.Task) string {
	switch {
	case t.Status == deep.StatusVerified:
		if s.Verify == "" {
			return "worker reported completion (no verify command defined)"
		}
		return "mission verify passed"
	case t.Attempts > 0:
		return truncate(strings.ReplaceAll(t.LastResult, "\n", " "), 120)
	case t.Blocker != "":
		return t.Blocker
	default:
		return "not started"
	}
}

func truncate(s string, n int) string {
	s = strings.TrimSpace(s)
	if len(s) <= n {
		return s
	}
	return s[:n-3] + "..."
}
