package main

const (
	diagnosticOK                      = "OK"
	diagnosticProviderUnreachable     = "PROVIDER_UNREACHABLE"
	diagnosticInstanceMissing         = "INSTANCE_MISSING"
	diagnosticInstanceNotRunning      = "INSTANCE_NOT_RUNNING"
	diagnosticSSHMetadataMissing      = "SSH_METADATA_MISSING"
	diagnosticSSHTCPUnreachable       = "SSH_TCP_UNREACHABLE"
	diagnosticSSHConnectionRefused    = "SSH_CONNECTION_REFUSED"
	diagnosticSSHAuthFailed           = "SSH_AUTH_FAILED"
	diagnosticSSHCommandFailed        = "SSH_COMMAND_FAILED"
	diagnosticRuntimeBinaryMissing    = "RUNTIME_BINARY_MISSING"
	diagnosticRuntimeProcessDead      = "RUNTIME_PROCESS_DEAD"
	diagnosticRuntimeProcessStarting  = "RUNTIME_PROCESS_STARTING"
	diagnosticModelDownloading        = "MODEL_DOWNLOADING"
	diagnosticModelVerifying          = "MODEL_VERIFYING"
	diagnosticModelLoadInProgress     = "MODEL_LOAD_IN_PROGRESS"
	diagnosticModelDownloadFailed     = "MODEL_DOWNLOAD_FAILED"
	diagnosticModelChecksumFailed     = "MODEL_CHECKSUM_FAILED"
	diagnosticRemotePortNotListening  = "REMOTE_PORT_NOT_LISTENING"
	diagnosticRemoteEndpointRefused   = "REMOTE_ENDPOINT_REFUSED"
	diagnosticRemoteEndpointTimeout   = "REMOTE_ENDPOINT_TIMEOUT"
	diagnosticRemoteEndpointHTTPError = "REMOTE_ENDPOINT_HTTP_ERROR"
	diagnosticTunnelProcessMissing    = "TUNNEL_PROCESS_MISSING"
	diagnosticTunnelProcessDead       = "TUNNEL_PROCESS_DEAD"
	diagnosticTunnelForwardInvalid    = "TUNNEL_FORWARD_INVALID"
	diagnosticLocalPortNotListening   = "LOCAL_PORT_NOT_LISTENING"
	diagnosticLocalPortConflict       = "LOCAL_PORT_CONFLICT"
	diagnosticLocalEndpointRefused    = "LOCAL_ENDPOINT_REFUSED"
	diagnosticLocalEndpointTimeout    = "LOCAL_ENDPOINT_TIMEOUT"
	diagnosticLocalEndpointHTTPError  = "LOCAL_ENDPOINT_HTTP_ERROR"
	diagnosticWatchdogMissing         = "WATCHDOG_MISSING"
	diagnosticDestroyUnconfirmed      = "DESTROY_UNCONFIRMED"
)
